version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"  # Expose Django's internal port
    volumes:
      - .:/app  # Sync local files to the container for development
    environment:
      - DEBUG=True
      - DB_NAME=bankdb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
    

  
